sx-project: exec-ce-dev-us
sx-geography: us
env-type: non-prod
portal-env: tst
env-stage: staging
ef-env: tst
topic-env: dev
ef-geography: eus2
ef-product: wms
databases:
  mongodb:
    - cluster-name: shipment-dev-us
      project-name: Cognitive Execution Shipment (DEV-US)
      tier: m10
  sqlserver-elasticpool:
    - name: ce-elasticpool
      tier: GeneralPurpose
      storage-size: 512GB
      core: 4
rateLimit:
  numberOfCalls: 500
  timeInSeconds: 10

