# .github/workflows/callee.yaml
name: "Callee Workflow"

on:
  workflow_call:
    inputs:
      input:
        required: true
        type: string

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print input
        run: |
          echo "Input: ${{ inputs.input }}"
