# .github/workflows/main.yaml
name: "Main Workflow"

on:
  workflow_dispatch:
    inputs:
      myString:
        description: Enter a string
        required: true
        type: string
jobs:
  call_reusable_workflow:
    uses: ./.github/workflows/mywf.yaml
    with:
      input: ${{ github.event.inputs.myString }}
