# .github/workflows/main.yaml
name: "Main Workflow"

on:
  push:
    branches:
      - main

jobs:
  call_reusable_workflow:
    uses: ./.github/workflows/mywf.yaml
    with:
      input: "hello world"
