name: Deploy container web to Stratosphere

on:
  push:
    branches:
      - 'main'

  workflow_dispatch:
    inputs:
      envType: 
        description: "Please select the Environment Type"
        required: true
        type: choice
        options: 
          - dev-us
          - psr-us
          - qa-us

env: 
  ENVIRONMENT: ${{ inputs.envType }}  # Set the environment variable based on the selected input.
  REALMS_MAPPING: ${{ format('envs/{0}/env-config.yaml', env.ENVIRONMENT) }}  # Construct path based on ENVIRONMENT.

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Deploy container web
        run: |
          echo "Deploying to environment: ${{ env.ENVIRONMENT }}"
          echo "Using realms mapping file: ${{ env.REALMS_MAPPING }}"
