jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect environment(s)
        id: detect_environment
        run: |
          # Create a JSON array from the input
          ENVIRONMENT_ARRAY=$(echo "${{ inputs.envType }}" | jq -R -s 'split(" ")')
          
          # Set the output variable to use in later steps
          echo "environment_array=$ENVIRONMENT_ARRAY" >> $GITHUB_OUTPUT

      - name: Use environment array
        run: |
          # Access the environment array output
          echo "The environment array is: ${{ steps.detect_environment.outputs.environment_array }}"
