name: Deploy container web to Stratosphere

on:
  push:
    branches:
      - 'main'
    paths:
       - 'ce/app-deployment/template/**'
       - 'envs/dev-us/web-container/**'
       - 'envs/psr-us/web-container/**'
       - 'envs/qa-us/web-container/**'

  workflow_dispatch:
    inputs:
      envType: 
        description: "Please select the Environment Type"
        required: true
        type: choice
        options: 
          - dev-us
          - psr-us
          - qa-us

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect environment(s)
        id: detect_environment
        run: |
          echo ${{ inputs.envType }} | jq -R 'split(" ")

      #- name: Confirm ENVIRONMENT variable is set
      #  run: |
      #    #/bin/bash  
      #    echo "The environment variable is: ${{ env.ENVIRONMENT }}"
