name: Detect Environment

on:
  push:
    paths:
      - dev/config.yaml
      - stage/config.yaml
      - prod/config.yaml

jobs:
  detect-config-change:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

