name: Deploy container web to Stratosphere

on:
  push:
    branches:
      - 'main'

  workflow_dispatch:
    inputs:
      envType: 
        description: "Please select the Environment Type"
        required: true
        type: choice
        options: 
          - dev-us
          - psr-us
          - qa-us

env:
  ENVIRONMENT: ${{ inputs.envType }}
  REALMS_MAPPING: envs/${{ inputs.envType }}/env-config.yaml

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Display Environment and Realms Mapping
        run: |
          echo "Deploying to environment: ${{ env.ENVIRONMENT }}"
          echo "Using realms mapping file: ${{ env.REALMS_MAPPING }}"
