name: Main Workflow

on: [push]

jobs:
  matrix_job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [10, 12, 14]
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.version }}

      - name: Call Reusable Workflow
        uses: ./.github/workflows/reusable-workflow.yml
        with:
          example_input: ${{ matrix.version }}
