name: Matrix Example

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node: [14, 16, 18]
        # You can also add "exclude" or "include" to customize combinations
        # exclude:
        #   - os: windows-latest
        #     node: 14
        # include:
        #   - os: ubuntu-latest
        #     node: 20

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm install

      - name: Run tests on ${{ matrix.os }} with Node.js ${{ matrix.node }}
        run: npm test

      - name: Upload test results
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: test-results-${{ matrix.os }}-node-${{ matrix.node }}
          path: test-results/
