name: Multi-Matrix Workflow

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev, qa, prod]      # First matrix dimension
        service: [service1, service2]     # Second matrix dimension
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Deploy
        run: |
          echo "Deploying ${matrix.service} to ${matrix.environment}"
          # Add your deployment commands here
