name: 2D Matrix Example

on:
  push:
    branches:
      - main

jobs:
  get_matrix:
    runs-on: ubuntu-latest
    outputs:
      bash_array: ${{ steps.bash_array.outputs.SERVICES }}
    steps:
      - name: Create BASH array from input
        id: bash_array
        run: |
          input="sample-service,config-service"
          IFS=',' read -ra services <<< "$input"
          
          echo "This is not very nice"
          echo "Services to be processed: ${services[@]}"

          echo "This is what GH likes"
          services_json=$(echo -n "["; for i in "${services[@]}"; do echo -n "\"$i\","; done | sed 's/,$//'; echo "]")
          

          echo "Services to be processed: ${services_json}"
          echo "SERVICES=$services_json" >> $GITHUB_OUTPUT

  deploy:
    needs: get_matrix
    strategy:
      matrix:
        env: [dev, staging, production]
        service: ${{ fromJson(needs.get_matrix.outputs.bash_array) }}

    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Deploy to ${{ matrix.env }} for ${{ matrix.service }}
        run: |
          echo "Deploying ${{ matrix.service }} to ${{ matrix.env }}"
