name: Reusable Workflow

on:
  workflow_call:
    inputs:
      example_input:
        required: true
        type: string

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Example Step
        run: echo "This is a reusable workflow step with input ${{ inputs.example_input }}"
