name: Second Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'The environment name'
        required: true

jobs:
  process-environment:
    runs-on: ubuntu-latest
    steps:
      - name: Process environment
        run: |
          echo "Processing second workflow for environment: ${{ github.event.inputs.environment }}"
