name: Main Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  call-reusable-workflow:
    uses: .github/workflows/reusable-workflow.yaml@main
    with:
      example_input: 'Hello, World!'
